### ISSUE TITLE
HTTP2 handling

### ISSUE THREAD

**Issue by rvansa** [RedHatPerf/SailRocket#16]
Currently we don't use HTTP2 though it's implemented. The default behaviour should be suggesting HTTP2 preference during ALPN (on secure connections), with an option to disable this. That's what most browsers do.

~~Cleartext HTTP2 (h2c) won't be supported ATM.~~ Actually it seems there already is some support to do the upgrade, so I'll add an option to force it.

In any case, this might require changes in HttpClientPool implementation as the ALPN may settle on different protocol than the preferred one.

**Comment by vietj** [comment]
@rvansa note that Vertx HttpClient handle both and provide pooling support for both, i.e it takes in account the concurrency if an HTTP/2 connection fallback to HTTP/1 and will open more connection

**Comment by vietj** [comment]
is vertx still used as HTTP client in this project ?

**Comment by rvansa** [comment]
@vietj We've dropped the Vertx HttpClient, now using only the plain Netty one.

**Comment by vietj** [comment]
what is the reason you dropped it ?

**Comment by rvansa** [comment]
@vietj There were two alternative implementations (Vertx and Netty) and naturally a third API to wrap them. Developing both of them would be cumbersome with little value, and since we try to make SailRocket close to zero-allocation (eventually we might rework the HTTP parsing to help us that goal as well), Netty which is a lower-layer (IIUC VertX client uses Netty, too) was an obvious candidate. We can simply have more control of what it does.

For example, as it goes with Java, Vertx API creates a HttpClientRequest for each request. We'd prefer all objects to be pre-allocated (pooled), and this is one place where we wouldn't be able to do so. Each handler would have to be a capturing one (to map the response to the user and request) which would turn into another allocation. 

What would Vertx API give us? Pooling of connections? That's not a hard problem once we isolate all resources to distinct eventloops.

**Comment by vietj** [comment]
@rvansa the main reason this code was developed with Vert.x in addition of Netty, is that because it provided a way to benchmark Vert.x HttpClient.

There are plenty of ways to benchmark a server (wrk, gatling, this project) but there are easy way to test the performance of a client.

When I _donated_ this code to this project I wanted to have this kept so I don't have to maintain the code I originally wrote and I can continue benchmarking the Vert.x HttpClient.

That's my explanation.

**Comment by vietj** [comment]
So basically it means I will have to continue using my original project for Vert.x QA and cannot use this one instead.

**Comment by vietj** [comment]
actually we wanted also to use this code to benchmark Vert.x EventBus too...

**Comment by vietj** [comment]
not cool @stalep

**Comment by rvansa** [comment]
@vietj I see, I didn't have this background - benchmarking client code was never the objective. I've checked with @stalep when removing the code and there were no objections. I'll think about ways to reintroduce it, then.

**Comment by rvansa** [comment]
@vietj How would you like to benchmark event bus? ATM we use eventbus as a nice way of communication between agents. We could add messaging to the simulation, too, though sharing the event bus for orchestration *and* benchmark does not sound like a good idea.

**Comment by vietj** [comment]
@rvansa the code that is interesting for us is the code the code around the Pacer for the event bus.

Basically what I want to have is a way to have SailRocket have a pluggable client.

So there is the Netty client, the Vert.x HttpClient but any other client.

A client being something that we define as something able to execute a task and provide an asynchronous result.

This way we can reuse reporting / percentile analysis for any kind of client.

**Comment by vietj** [comment]
Perhaps I can help define the need and have an EventBus testing in this project or another ?

**Comment by vietj** [comment]
The main issue I found by doing my own client were:

1/ have the ability to execute as quickly as possible tasks (i.e my first attempt did not create enough pressure on the client to benchmark correctly the server)
2/ have a tool
3/ have reporting of latencies
4/ avoid coordinated omission

**Comment by vietj** [comment]
and the project I created was the answer to that

**Comment by rvansa** [comment]
@vietj Can I get hold of you on IRC (can't see you on Freenode #vertx)?

**Comment by vietj** [comment]
pinged you

**Comment by vietj** [comment]
we preferably now uses gitter for discussion https://gitter.im/eclipse-vertx/vertx-users

**Comment by rvansa** [comment]
HTTPS/HTTP2 stuff done.
