### ISSUE TITLE
Header validation

### ISSUE THREAD

**Issue by johnaohara** [RedHatPerf/SailRocket#8]
Update http client to allow for custom header validators

**Comment by stalep** [comment]
Not sure if one base type of validators would be best... atm we have just Validator<T>.validate(Supplier<T> supp) and then StepImpl have List<Validator<?>> validators.
what if we had:
interface StatusValidator implements Validator<Integer>
interface HeaderValidator implements Validator<Map<String,String>>
interface BodyValidator implements Validator<String>

then we could have a Validators class ala:
class Validators {
  HeaderValidator headerValidator();
  StatusValidator statusValidator();
  BodyValidator bodyValidator();
}
